server:
  port: 8084

spring:
  application:
    name: servico-shipping
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  #datasource:
  #  url: jdbc:mysql://localhost:3306/authdb?createDatabaseIfNotExist=true
  #  username: root
  #  password: janith
  #  driver-class-name: com.mysql.cj.jdbc.Driver

  #  jpa:
  #    hibernate:
  #      ddl-auto: update
  #    show-sql: true
  #    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

  instance:
    prefer-ip-address: true
    ip-address: ${HOST_IP:127.0.0.1}