server:
  port: 8084

spring:
  application:
    name: servico-shipping

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

  instance:
    prefer-ip-address: true
    ip-address: ${HOST_IP:127.0.0.1}