server:
  port: 8080

spring:
  application:
    name: servico-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: servico-auth
          uri: lb://servico-auth
          predicates:
            - Path=/auth/**

        - id: servico-catalogo
          uri: lb://servico-catalogo
          predicates:
            - Path=/catalogo/**

        - id: servico-carrinho
          uri: lb://servico-carrinho
          predicates:
            - Path=/cart/**

        - id: servico-shipping
          uri: lb://servico-shipping
          predicates:
            - Path=/order/**

        - id: servico-query
          uri: lb://servico-query
          predicates:
            - Path=/query/**

        - id: servico-saga
          uri: lb://servico-saga
          predicates:
            - Path=/checkout/**

        #- id: gateway-composition
        #  uri: http://dummy-host
        #  predicates:
        #    - Path=/gateway/addBookToCart

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

  instance:
    prefer-ip-address: true
    ip-address: ${HOST_IP:127.0.0.1}

app:
  jwtSecret: B374A26A71490437AA024E4FADD5B497FDFF1A8EA6FF12F6FB65AF2720B59CCF
