version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: janith
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  zookeeper:
    image: bitnami/zookeeper:3.8
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes

  kafka:
    image: bitnami/kafka:3.2
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: yes
    depends_on:
      - zookeeper

  servico-eureka:
    build:
      context: .
      dockerfile: Servico-Eureka/Dockerfile
    ports:
      - "8761:8761"

  servico-query:
    build:
      context: .
      dockerfile: Servico-Query/Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/querydb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: janith
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://servico-eureka:8761/eureka
    depends_on:
      mysql:
        condition: service_healthy
      kafka:
        condition: service_started
      servico-eureka:
        condition: service_started
    ports:
      - "8085:8085"

  servico-shipping:
    build:
      context: .
      dockerfile: Servico-Shipping/Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/shippingdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: janith
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://servico-eureka:8761/eureka
    depends_on:
      mysql:
        condition: service_healthy
      kafka:
        condition: service_started
      servico-eureka:
        condition: service_started
    ports:
      - "8084:8084"

  servico-catalogo:
    build:
      context: .
      dockerfile: Servico-Catalogo/Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/catalogodb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: janith
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://servico-eureka:8761/eureka
    depends_on:
      mysql:
        condition: service_healthy
      kafka:
        condition: service_started
      servico-eureka:
        condition: service_started
    ports:
      - "8082:8082"

  servico-carrinho:
    build:
      context: .
      dockerfile: Servico-Carrinho/Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/carrinhodb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: janith
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://servico-eureka:8761/eureka
    depends_on:
      mysql:
        condition: service_healthy
      kafka:
        condition: service_started
      servico-eureka:
        condition: service_started
    ports:
      - "8083:8083"

  servico-gateway:
    build:
      context: .
      dockerfile: Servico-Gateway/Dockerfile
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://servico-eureka:8761/eureka
    depends_on:
      servico-eureka:
        condition: service_started
    ports:
      - "8080:8080"

  servico-auth:
    build:
      context: .
      dockerfile: Servico-Auth/Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/authdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: janith
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://servico-eureka:8761/eureka
    depends_on:
      mysql:
        condition: service_healthy
      servico-eureka:
        condition: service_started
    ports:
      - "8081:8081"

  servico-saga:
    build:
      context: .
      dockerfile: Servico-Saga/Dockerfile
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://servico-eureka:8761/eureka
    depends_on:
      kafka:
        condition: service_started
      servico-eureka:
        condition: service_started
    ports:
      - "8086:8086"