CREATE DATABASE IF NOT EXISTS querydb;
CREATE DATABASE IF NOT EXISTS shippingdb;
CREATE DATABASE IF NOT EXISTS catalogodb;
CREATE DATABASE IF NOT EXISTS carrinhodb;
CREATE DATABASE IF NOT EXISTS authdb;