server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: catalog-service
          uri: http://localhost:8082
          predicates:
            - Path=/books/**, /search, /updatequantity/**

        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
