apiVersion: apps/v1
kind: Deployment
metadata:
  name: servico-saga
spec:
  replicas: 3
  selector:
    matchLabels:
      app: servico-saga
  template:
    metadata:
      labels:
        app: servico-saga
    spec:
      containers:
        - name: servico-saga
          image: MAD.ocir.io/axvi0ijuogkl/servico-saga:old
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8086
              protocol: TCP
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
      imagePullSecrets:
        - name: ocirsecret
---
apiVersion: v1
kind: Service
metadata:
  name: servico-saga-lb
  labels:
    app: servico-saga
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "100"
spec:
  type: ClusterIP
  ports:
    - port: 8086
  selector:
    app: servico-saga