apiVersion: apps/v1
kind: Deployment
metadata:
  name: servico-auth
spec:
  replicas: 3
  selector:
    matchLabels:
      app: servico-auth
  template:
    metadata:
      labels:
        app: servico-auth
    spec:
      containers:
        - name: servico-auth
          image: MAD.ocir.io/axvi0ijuogkl/servico-auth:v6
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/authdb
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: janith

      imagePullSecrets:
        - name: ocirsecret
---
apiVersion: v1
kind: Service
metadata:
  name: servico-auth-lb
  labels:
    app: servico-auth
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "100"
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: servico-auth
