apiVersion: apps/v1
kind: Deployment
metadata:
  name: servico-gateway
spec:
  replicas: 3
  selector:
    matchLabels:
      app: servico-gateway
  template:
    metadata:
      labels:
        app: servico-gateway
    spec:
      containers:
        - name: servico-gateway
          image: MAD.ocir.io/axvi0ijuogkl/servico-gateway:v10
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
      imagePullSecrets:
        - name: ocirsecret
---
apiVersion: v1
kind: Service
metadata:
  name: servico-gateway-lb
  labels:
    app: servico-gateway
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "100"
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: servico-gateway
